# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: false
sudo: false
cache: packages

before_install:
  - Rscript -e 'Packages <- c("Rcpp", "RcppArmadillo", "vegan", "dplyr", "reshape2", "gridExtra", "ggplot2", "ggthemes"); install.packages(Packages); lapply(Packages, library, character.only = TRUE)'

env:
  - R_KEEP_PKG_SOURCE=yes
